### ISSUE TITLE
[BUG] Not showing png in VS Code

### ISSUE THREAD

**Issue by infilite** [markmap/markmap#294] opened 2024-12-10 04:22 UTC
- [x] I have searched for existing issues that already reported this problem and found none
- [x] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Environment:**

- OS: [Windows10]
- VSCode: [VSCode-win32-x64-1.95.3]

**Additional context**

![image](https://github.com/user-attachments/assets/9838f3b9-fd06-4b95-bec3-32edf1804483)

**Comment by infilite** [comment] 2024-12-10 04:23
![image](https://github.com/user-attachments/assets/db9f7ba1-901b-49a7-bf23-002699b5bbdf)
Not showing png

**Comment by infilite** [comment] 2024-12-11 01:33
> ![image](https://private-user-images.githubusercontent.com/88495273/394112972-db9f7ba1-901b-49a7-bf23-002699b5bbdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODA4NzYsIm5iZiI6MTczMzg4MDU3NiwicGF0aCI6Ii84ODQ5NTI3My8zOTQxMTI5NzItZGI5ZjdiYTEtOTAxYi00OWE3LWJmMjMtMDAyNjk5YjViYmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDAxMjkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4OTliNzc0YzY2NDkxMzFmNGRkMGRhMTEzMWQzNDNiYzQwZjg1YWM5ZjJmZGJhYzdjOWM4ZGZmYzVhNDNlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zqfltrBHo0Gs1mbQJouS02OFmeFk8nDsTW5JO8znbl0) Not showing png


![image](https://github.com/user-attachments/assets/f33d8e7f-06c4-4874-98f4-5f6d3e3ba6e0)

**Comment by gera2ld** [comment] 2024-12-13 04:12
Duplicate of markmap/markmap-vscode#36

**Closed by gera2ld** 2024-12-13 04:12 UTC
Labels: bug
