### ISSUE TITLE
[BUG] Math expressions are printed top left of the map instead of being on their Katex branch in Safari

### ISSUE THREAD

**Issue by Emasoft** [markmap/markmap#172] opened 2023-05-19 16:37 UTC
- [X] I have searched for existing issues that already reported this problem and found none
- [X] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**
In Safari iOS the math expressions are printed in the top left part of the screen instead of being on their branch.

**To Reproduce**

Just open the default link on Safar iOS (ipad):
https://markmap.js.org/repl

**Expected behavior**

The math expression should appear positioned on the correct Katex branch.

**Actual behavior**

Here is a screenshot:

![IMG_6562](https://github.com/markmap/markmap/assets/713559/21166fd6-a88f-4744-bffe-8d8e1fdd9eff)

**Environment:**

- OS: iOS or iPadOS 16.4.1 (a)
- Browser: Safari
- Browser Version: iOS or iPadOS 16.4.1 (a)

**Comment by gera2ld** [comment] 2023-05-20 14:51
Duplicate of #15

**Closed by gera2ld** 2023-05-20 14:51 UTC
Labels: bug
