### ISSUE TITLE
Text is removed when exporting to SVG

### ISSUE THREAD

**Issue by RobertTalbert** [markmap/markmap#79] opened 2021-06-01 16:21 UTC
First of all, I love this tool. Thanks so much for making it. 

I just created a map using this Markdown list: https://gist.github.com/RobertTalbert/c21318f02451a5156116598484092235 It's pretty big and has a bit of MathJax in it. When I exported it to SVG, the "tree" part of the mindmap was there but none of the text appeared. Screenshot: https://ibb.co/r7SJzZY  (That's from a PNG created from the SVG, but the SVG looks the same.) I tried this as well with the sample mindmap that appears when you access the site, and it was the same problem --- the map is there but no text.

**Comment by gera2ld** [comment] 2021-06-03 00:26
Glad you like it.

How did you export the SVG? I tried to export at <https://markmap.js.org/repl#?d=gist:c21318f02451a5156116598484092235/mth225-LO-version1.md> and the text stayed.

**Comment by RobertTalbert** [comment] 2021-06-17 20:03
Sorry this is late, I didn't see the notification! I was using CloudConvert.com

**Comment by Kibouo** [comment] 2021-06-18 16:44
The SVG itself looks fine. The problem is during conversion. Loading the SVG into GIMP also fails (only coloured lines and nodes are visible).

**Comment by gera2ld** [comment] 2024-12-30 09:37
Closing as it doesn't seem to be a markmap issue.

**Closed by gera2ld** 2024-12-30 09:37 UTC
