### ISSUE TITLE
[feature-request]download single offline html in try-it-out

### ISSUE THREAD

**Issue by HuangShumin** [markmap/markmap#138] opened 2022-10-31 03:32 UTC
The downloaded standalone html can be opened in an air-gapped environment without Interent Access

**Comment by HuangShumin** [comment] 2022-10-31 16:59
Currently when I embed all assets, got error:

404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

**Comment by gera2ld** [comment] 2022-11-05 00:39
Sorry, can you elaborate what you have done? What do you mean by "embed all assets" and got 404?
AFAICT there is no way to download an offline HTML with all assets embedded for now since the plugins still depends on CDN.

**Comment by gera2ld** [comment] 2023-02-13 13:04
Closing as duplicate of #147

**Closed by gera2ld** 2023-02-13 13:04 UTC

**Comment by HuangShumin** [comment] 2023-02-14 03:16
Cool Gera2ld, fix it!!!
